### ISSUE TITLE
I'm not a huge fan of this

### ISSUE THREAD

**Issue by dalcde** [SpectralSequences/sseq#1]
I don't like the idea of telling the users how they should arrange their repository. I prefer if every repository is individually installable, but may require stringing some dependencies together yourself. It makes it easier for people to try individual pieces out, and for travis to do so too. I don't see the advantage of having a centralized way of doing so, especially since people are only going to do it once.

**Comment by hoodmane** [comment]
Yeah I'm not sure this is a great idea, I'm just messing around.
Currently the individual repositories don't have to be installed in any particular location. I think the idea of having environment variables giving the paths to installed repositories is decent. 

I think there are a lot of people who won't use our code at all if they have to clone four repositories and create four symlinks in order to get it to work. We at least should have some sort of easy install script that resolves the dependencies automatically.

**Comment by dalcde** [comment]
I think the install script for, say, `steenrod_calculator` should check for the presence of `ext`. If it is not present, it can ask the user if we should clone it or symlink it from somewhere else.

**Comment by dalcde** [comment]
I have the reverse issue that if the build instructions for the repository is "download this other repository and then run another script from there", it could be offputting

**Comment by hoodmane** [comment]
Well I can get rid of the "clone the other repository" issue by copying `bin/_make_repository_link.sh` into each individual repository `bin` folder and then just define a separate environment variable for each repository.

I don't really understand the distinction between asking people to clone the ext repository because the steenrod_calculator depends on it and asking people to clone this sseq repository because the steenrod_calculator depends on it. Either way we are basically saying "download this other repository and then run another script from there." 

I think what's worse is having really complicated build instructions for the user. If they have to manually create four sym links then chances are at least one of them will have mistakes that they will need to debug.

I think with a setup like this we could allow users to say "just clone whatever repositories you need to build this one" and have it act like a mini package manager. I think it's a good idea to allow people to manually create the symlinks if they prefer that though.

**Comment by hoodmane** [comment]
Anyways even if we don't want to ask people to clone sseq, I think it's good to have a master repository so we can have a listing of what is here and a global issues board. Is there some better place to put a master readme / issues that involve multiple repositories?

**Comment by dalcde** [comment]
On Sat, Mar 21, 2020 at 03:55:12PM -0700, Hood Chatham wrote:
>I don't really understand the distinction between asking people to clone the ext repository because the steenrod_calculator depends on it and asking people to clone this sseq repository because the steenrod_calculator depends on it. Either way we are basically saying "download this other repository and then run another script from there."

I think this is a matter of logical order. I'd prefer if the first step
of installing steenrod_calculator is cloning steenrod_calculator, and
not cloning some other repository that downloads steenrod_calculator for
you.

I think a reasonable compromise is to do a `git clone --depth 1` for the
user if `ext` is not present, but if the user symlinks `ext` beforehand
this will not be done. Doing a `--depth 1` clone is usually pretty fast
anyway.

>I think with a setup like this we could allow users to say "just clone whatever repositories you need to build this one" and have it act like a mini package manager. I think it's a good idea to allow people to manually create the symlinks if they prefer that though.

I precisely don't like repositories that tell me to install a package
manager to use it. I do not object to having a "package manager". I just
object to the install script refusing to run without the package
manager.

> Anyways even if we don't want to ask people to clone sseq, I think it's good to have a master repository so we can have a listing of what is here and a global issues board. Is there some better place to put a master readme / issues that involve multiple repositories?

I agree. This repository can serve this purpose.

**Comment by hoodmane** [comment]
> I'd prefer if the first step of installing steenrod_calculator is cloning steenrod_calculator, and not cloning some other repository that downloads steenrod_calculator for you.

Yeah that makes sense. If I just copy `_make_repository_link.sh` into each bin directory I can get rid of that dependency. It makes modifying `_make_repository_link.sh` a bit more annoying, but that isn't a huge deal and as you say it isn't worth having a weird install order.

> a reasonable compromise is to do a `git clone --depth 1`
What does `--depth 1` do?

**Comment by dalcde** [comment]
`--depth 1` only downloads the current master and not the history

**Comment by hoodmane** [comment]
It takes a while to run `cargo build release`. I don't think the default behavior should be to build a copy of `ext` for every separate repository.

**Comment by dalcde** [comment]
I don't think we can avoid that. In our previous version of `ext` where we split things into library and binary, we also build two copies of ext.

**Comment by hoodmane** [comment]
Did they have different compile flags?
Is Cargo not willing or able to link an existing library like `crate/target/lib.so`? Does it need symbols or information that are missing from the compiled library? If so that seems like a weird deficiency of Rust. But yeah if that is necessary then you have a good point.

**Comment by hoodmane** [comment]
Clearly it can do a partial rebuild because if I don't change the compile flags it will reuse previously built packages. It seems to me like this issue of building many copies of `ext` must just be a mistake in our config files.

**Comment by hoodmane** [comment]
Also, how were you getting it to compile `ext` with `-O3` but not `ext-websocket`?
I copied the lines:
```toml
[profile.dev.package."*"]
opt-level = 3
```
from your config file and that was working until we split the repositories but now it doesn't work anymore.

**Comment by dalcde** [comment]
The last one *should* work.

I think cargo cannot link an external library because it needs to be able to recompile if necessary (different flags, different compiler, etc.)

**Comment by hoodmane** [comment]
But what if you are compiling with the same compiler and the same flags (as I think we are doing in our case)? Shouldn't it then not need to recompile? Isn't that what it's doing with required crates? Not recompiling them if nothing in their source changed and no compile flags changed?

**Comment by hoodmane** [comment]
Okay a proposal for the install script. Two options:
* `install auto`: we ask permission to clone all missing dependent repositories into parent directory of current repository and set relevant environment variables. Perhaps can choose to clone with depth 1 or normally, and whether to clone into parent directory or working directory.
* `install manual`: We check for necessary symlinks (or you could just clone the whole repository inside of this folder) by checking that the origin of the repository is correct. If symlink is missing or wrong but a relevant environment variable is set, we check that the environment variable is a path to a valid repository and automatically create symlink. If neither of the above exist, we quit with a message saying what's wrong.

**Comment by dalcde** [comment]
I think all of these options are fairly easy to perform. If our goal is to minimize complexity, we are better off picking the simplest and lowest-cost option (which I believe is `git clone --depth `) and then explaining the situation to the user. They can decide to ignore it and move on with their lives, or read it and do something else.

**Comment by hoodmane** [comment]
I don't like the idea that this proposal would take a dependency DAG and copy all the nodes to convert into a tree:
```
     A              A
   / | \          / | \
  B  C  D   ==>  B  C  D
   \ | /         |  |  |
     E           E  E  E
```
Combining this with our current approach of splitting into many small repositories seems like it could lead to cloning many many copies of the same repository. 

It's not really that hard for us to write an auto installer that works correctly. I really like package managers -- cargo, pip, npm, tlmgr, etc are all really great things. I have never wanted to manually install a Python wheel. And all of these package managers can figure out how to set a flag to record the fact that they have already installed something to avoid the DAG to tree conversion.

As I said I can wget an installer script and automatically set up sym links to the dependencies if the user wants an auto install. It's a good idea to separate out the "do stuff" part of the install script anyways, so if you or Travis want a manual install you can avoid wgetting that script then just run the rest of the install code. I think a script `bin/install_auto.sh` that sets up dependencies and then calls `bin/install_manual.sh` should be fine.

**Comment by dalcde** [comment]
I think none of the package manager code has to go into the install
scripts of the individual packages. The install script clones only if
ext is not present, so the package manager simply has to

  1. clone
  2. symlink
  3. run the install script

in that order. This is also consistent with how a lot of package
managers behave --- the library itself is not tied to any particular
package manager and can be installed by itself.

I also think there is a huge difference between this situation and the
situation package managers are used to deal with. Usually you don't care
where the package manager puts your files, and everything happens behind
the scenes. This is when package managers shine.

However, in this case people usually have some opinion where they want
to put the folders since they'll access it directly; they might want
some of it to track their own fork, etc. Thus I think it is important
for the build system to be relatively simple and independent of any
packaging decision.

**Comment by hoodmane** [comment]
This all makes sense. As a developer, I _definitely_ care where the individual repositories go and want to be able to swap out components. 

I think most of our users won't care so much where the files go as long as they can use the package. In particular, if we put all of them next to each other in some specified directory, then that would probably be great for most people.  They will probably want to know where the code goes, but not modify it too much at first. 

So how about this: Put this "simple package manager" that implements the logic you described in `sseq/bin` and then otherwise keep the install scripts the way they are. In the READMEs, advertise that if what you want is to get the code running as quickly as possible, clone `sseq` and run the package manager and it will set everything up as automatically as possible? Then give manual installation instructions with a more complete description of the dependencies and how they need to be arranged?

**Comment by dalcde** [comment]
Sounds good to me.
