### ISSUE TITLE
A question about the input at odd prime

### ISSUE THREAD

**Issue by DZaiger** [SpectralSequences/sseq#122]
First of all, thank you all for making this really powerful program! I have a small question: I would like to compute certain Adams spectral sequence at p = 3. In your sseq/ext/MODULE-SPEC.md file, you have a template which is y(2), but I don't understand why the input for q_part is "4294967292"? Should I convert it to a binary? If yes, why this gives a spectrum with homology F_p[ξ₁, ξ₂][τ₁, τ₂]?

**Comment by JoeyBF** [comment]
Thanks for the kind words. For this example, we are taking the cohomology of the Steenrod algebra quotiented by the subalgebra given by the profile described in the `profile` block.

- `"truncated": false` says that the unspecified entries of the p-part will default to infinity instead of zero,
- `"p_part": [0, 0]`, together with the above, says that the profile function will not include $\xi_1$ or $\xi_2$ but will include every other $\xi_i$,
- `"q_part": 4294967292` says that the profile function will not include $\tau_1$ or $\tau_2$ but will include every other $\tau_i$. This number is a bitmask indicating which $\tau_i$ is included, where 1 = included. So since 4294967292 = 0b1111 1111 1111 1100, all $\tau_i$ except the first two are included.

**Comment by DZaiger** [comment]
Now I see, thank you for your careful explanation!
